apiVersion: v1
kind: Secret
metadata:
  name: nodejs-app-secret
  namespace: production

type: Opaque

stringData:
  APP_NAME: "NodeJS Production App"
  DB_HOST: "mysql.production.svc.cluster.local"
  DB_USER: "admin"
  DB_PASSWORD: "Password@123"
