pipeline {
    agent any

    environment {
        AWS_REGION     = "us-east-1"
        AWS_ACCOUNT_ID = "471623014951"
        ECR_REPOSITORY = "devops-prod"
        IMAGE_TAG      = "devops-prod-${BUILD_NUMBER}"
        CLUSTER_NAME   = "aws-prod-cluster"
        NAMESPACE      = "production"
    }

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                sh '''
                    echo "===== Git ====="
                    git --version

                    echo "===== Node ====="
                    node -v

                    echo "===== NPM ====="
                    npm -v

                    echo "===== Docker ====="
                    docker --version

                    echo "===== Kubectl ====="
                    kubectl version --client

                    echo "===== AWS CLI ====="
                    aws --version

                    echo "===== Current AWS Identity ====="
                    aws sts get-caller-identity

                    echo "===== Kubernetes Nodes ====="
                    kubectl get nodes
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app') {
                    sh 'npm ci'
                }
            }
        }

        stage('Application Health Check') {
          steps {
            dir('app') {
              sh '''
                echo "Starting Node.js application..."

                nohup npm start > app.log 2>&1 &
                APP_PID=$!

                echo "Waiting for application to start..."
                sleep 10

                echo "Checking health endpoint..."
                curl --fail http://localhost:3000/health

                echo "Stopping application..."
                kill $APP_PID
            '''
          }
        }
      }
        stage('Docker Build') {
          steps {
            dir('app') {
              sh '''
                echo "Building Docker Image..."

                docker build \
                -t ${ECR_REPOSITORY}:${IMAGE_TAG} \
                -t ${ECR_REPOSITORY}:latest .

                echo "Docker Image Built Successfully"

                docker images | grep ${ECR_REPOSITORY}
            '''
        }
    }
}
         stage('Trivy Image Scan') {
           steps {
             dir('app') {
               sh '''
                echo "Scanning Docker image..."

                trivy image \
                --severity HIGH,CRITICAL \
                --exit-code 0 \
                ${ECR_REPOSITORY}:${IMAGE_TAG}
            '''
        }
    }
}
        stage('Login to Amazon ECR') {
          steps {
            sh '''
            echo "Logging into Amazon ECR..."

            aws ecr get-login-password --region ${AWS_REGION} | \
            docker login --username AWS --password-stdin \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

            echo "Successfully logged into Amazon ECR"
        '''
    }
}
    stage('Tag & Push Docker Image') {
    steps {
        sh '''
            echo "Tagging Docker image..."

            docker tag \
            ${ECR_REPOSITORY}:${IMAGE_TAG} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

            echo "Pushing Docker images to Amazon ECR..."

            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}

            echo "Docker images pushed successfully."
        '''
    }
}
    stage('Deploy to Amazon EKS') {
    steps {
        dir('app') {
            sh '''
                echo "Deploying Kubernetes manifests..."

                kubectl apply -f k8s/namespace.yaml
                kubectl apply -f k8s/configmap.yaml
                kubectl apply -f k8s/secret.yaml
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml

                echo "Deployment completed successfully."
            '''
        }
    }
}
    stage('Verify Deployment') {
    steps {
        sh '''
            kubectl get all -n production

            kubectl rollout status deployment/nodejs-app -n production
        '''
       }
    }
}


   post {
        success {
            echo 'Pipeline executed successfully.'
        }

        failure {
            echo 'Pipeline failed.'
        }

        always {
            cleanWs()
        }
    }
}